Connecting to backend
graywolftech/gwa pull request #20
Opened 2020-10-19 19:26 UTC by mjsampson

- reading graphframes as input added 
- writing graphframes as output added with unit test 
- job_id and investigation_id for creating new  dataset_versions is pulled from gwa.json config file now 
- dataset schema and metadata pulled from dataframe/graphframe now 
- parsing s3 path to s3a path added (update of get_path util function)

2020-10-19 19:37 UTC, jamieserrano commented on gwa/output.py
> +                    "overwrite"
maybe we shouldn't have "overwrite" mode active, in case there's some unique edge case where two datasets were created near the same time, one would get an error when going to write. Thoughts??

2020-10-19 19:39 UTC, jamieserrano commented on gwa/output.py
> +                    "overwrite"
additional comment here instead of adding it to the other locations in out.py where overwrite mode is specified

2020-10-19 19:57 UTC, jamieserrano approved these changes

2020-10-19 20:19 UTC, mjsampson commented on gwa/output.py
> +                    "overwrite"
change made! Good idea

2020-10-19 23:44 UTC, jsmith requested changes

2020-10-19 23:44 UTC, jsmith commented on gwa/config.py
> +            "https://msa-prod.lemmi.be/"
We'll probably have to support staging, right?

2020-10-19 23:44 UTC, jsmith commented on gwa/output.py
> +                if new_dataset == "new_dataset":
This is a bit confusing. I think getting rid of `new_dataset` and just putting the `type(version) != int` it much clearer (and moving the comment)

2020-10-19 23:44 UTC, jsmith commented on gwa/output.py
> +                )
As it stands, I think we could get into some weird states where the two executables are writing at the same time to the same version. Imagine that two executables call `get_dataset_latest` but since none have actually published a new version, the function returns the same version then, each publishes that version (which is currently *ok* with our current system) and then each uploads their data to s3 in the same folder. There are a few things we could do to fix this I think!

2020-10-19 23:44 UTC, jsmith commented on gwa/output.py
> +                    )
Do we actually need this? In the `populate_gp_dataset_version` endpoint, we call:

```python
ds = GPDataset.get_or_create(db, name)
```

which should create the dataset if it doesn't exist.

2020-10-19 23:44 UTC, jsmith commented on gwa/util/graywolf_interface.py
> +    # works
Also.... these comments can probably go 🤣

2020-10-20 16:33 UTC, mjsampson commented on gwa/output.py
> +                if new_dataset == "new_dataset":
I made some changes to this in my recent push!

2020-10-20 16:34 UTC, mjsampson commented on gwa/output.py
> +                )
I agree there are edges case we could fix! Right now lets get a first pass then we can refine. There are also issues if we create 
1. dataset
and 
2. dataset version
but the corresponding data write to s3 fails. So in our sql database it says the dataset version exists but when we try to query it it doesn't

2020-10-20 16:35 UTC, mjsampson commented on gwa/output.py
> +                    )
this is a question for @jamieserrano

2020-10-20 16:36 UTC, mjsampson commented on gwa/util/graywolf_interface.py
> +    # works
i agree. If someone else could do this that would be great I need to prep for a pitch!

2020-10-20 16:38 UTC, jamieserrano commented on gwa/config.py
> +            "https://msa-prod.lemmi.be/"
the environment is given in the config, I can add a check here

2020-10-20 16:50 UTC, jamieserrano commented on gwa/output.py
> +                    )
I was unaware of the get_or_create method for datasets, called in the `populate_gp_dataset_version` 
so this would remove the requirement to call
``` if create_new_dataset:
                    container.GrayWolfInterface().populate_gp_dataset(
                        self.name, investigation_id=gwa_config.investigation_id
                    )
```

and remove the `create_new_dataset` variable all together

2020-10-20 16:50 UTC, jamieserrano commented on gwa/output.py
> +                    )
I'll test this out

2020-10-20 16:50 UTC, jamieserrano commented on gwa/util/graywolf_interface.py
> +    # works
on it!

2020-10-20 16:52 UTC, mjsampson commented on gwa/config.py
> +            "https://msa-prod.lemmi.be/"
yes! Since the gwa library will be user facing though I'm not sure how we should manage developer only configs. I think this requires more thought

2020-10-20 17:24 UTC, merged